Sprint 2
fennyflop/middle.messenger.praktikum.yandex pull request #2
Opened 2022-08-06 19:34 UTC by fennyflop

2022-08-06 21:10 UTC, agadoev commented on src/modules/view-modules/page.ts
> +// Page('.main', alert, {
Закомментированный код лучше стараться не держать в репозитории. Он отвлекает и увеличивает мыслительную нагрузку + загрязняет код. При чтении этого файла программист будет задумывать "а зачем нужен этот код?". Если код может пригодиться в будущем - его всегда можно будет посмотреть в системе контроля версий

2022-08-06 21:31 UTC, agadoev requested changes
Привет) спасибо за работу, довольно неплохо, хотя есть еще, над чем поработать. Из основного, что стоит исправить - валидацию и почистить код от комментариев

2022-08-06 21:31 UTC, agadoev commented on src/modules/view-modules/block.ts
> +import EventBus from "./event-bus";
Скорее всего view-modules не самое подходяшее название для этого каталога. Классы, которые тут хранятся, являются основой приложения, его ядром. Лучше оперировать более устоявшимся термином core, чем придумывать что-то свое. Это поможет новеньким людям в проекте быстрее влиться.

2022-08-06 21:31 UTC, agadoev commented on src/pages/change-password/change-password.tmpl.ts
> +// {{> input name="old_password" placeholder="Старый пароль" type="password" }}
Стоит убрать закомментированный код (объяснил почему в другом комменте)

2022-08-06 21:31 UTC, agadoev commented on src/modules/view-modules/page.ts
> +// Page('.main', alert, {
Закомментированный код лучше стараться не держать в репозитории. Он отвлекает и увеличивает мыслительную нагрузку + загрязняет код. При чтении этого файла программист будет задумывать "а зачем нужен этот код?". Если код может пригодиться в будущем - его всегда можно будет посмотреть в системе контроля версий

2022-08-06 21:31 UTC, agadoev commented on src/pages/change-password/change-password.ts
> +      return "Password should have at least 8 characters, one number, one uppercase letter and one lowercase letter.";
Смотри, тут файл с логикой валидации. При этом каждая функция-валидатор проверяет значение на валидность и возвращает строку текста для отображения на экране.

В программировании есть хороший принцип разделения ответственностей, который гласит, что функция (модуль, класс и тд.) должны иметь одну и только одну причину для изменения. Сейчас эти функции имеют две причины для изменения, потому что у них две ответственности.

Решить какой текст отображать - это задача вьюхи, а не функции валидатора. По хорошему, эти функции должны возвращать boolean, а во вьюехе уже подставляться текст в зависимости от результата валидации. Так же неплохо было бы написать type для функций валидаторов, указав возвращаемое значение

2022-08-06 21:31 UTC, agadoev commented on src/pages/change-password/change-password.ts
> +      !new RegExp(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$/).test(value)
Попробуй вынести regexp в отдельный файл. Не очень красиво смешить regexp, строковые константы с исходным кодом, потому что они могут меняться и удобнее будет их менять в отдельном файле, чем лезть в функцию. Вообще, есть хороший принцип из SOLID, Open Closed Principle, который гласит, что код вообще лучше не изменять, а дописывать новый. Понятно, что так может быть только в иделаьном мире, но к такому надо стремиться

SOLID - очень полезная вещь, т.к. эти принципе не зависят от технологии, языка или фреймворка и универсальны везде. Прочитать про них можно в книге "Чистая архитектура" Роберта Мартина

2022-08-06 21:31 UTC, agadoev commented on src/modules/http/http.ts
> +  request = (url: string, options: IRequest = {}, timeout = 5000) => {
Третьим параметром передается timeout, хотя он есть уже в объекте options. Давай оставим какой-то один вариант для timeout, чтобы не возникало путаницы

2022-08-08 05:49 UTC, agadoev commented
Привет)
Ты почти все поправил, код стал куда лучше. Однако я не увидел очень важного изменения - отрефакторить функции-валидаторы так, чтобы они возвращали не строку, а boolean. Это правда важно, потому что код сейчас сложно будет поддерживать. Если не очень понятно как это сделать - обратись к ментору. Я работу принимаю, потому что в целом все задания выполнены и код почищен, однако разберись, пожалуйста, с этим вопросом, перед тем, как мержить
Удачи в третьем спринте :)

2022-08-11 15:01 UTC, fennyflop commented
d

2022-08-11 15:02 UTC, merged